### ISSUE TITLE
Sending bundle as tx before new block is created

### ISSUE THREAD

**Issue by Vid201** [Vid201/silius#105]
Synchronize with execution client on timing for sending bundles. This should probably be right before the next block.

**Comment by zsluedem** [comment]
@Vid201 Could you elaborate more on this one? What do you mean right before the next bloek?

**Comment by Vid201** [comment]
> @Vid201 Could you elaborate more on this one? What do you mean right before the next bloek?

TBH I am not quite sure what I meant here now. That was the idea to prevent front-running and if sent just before the next block, bundle is not in the public tx pool for the long time. But it's probably to use flashbots or conditional endpoint if available.

**Comment by zsluedem** [comment]
I think it is not possible to do that unless you are a block builder.

**Comment by Vid201** [comment]
> I think it is not possible to do that unless you are a block builder.
> 
> Maybe it makes more sense to change the issue to talk about "Integration with block builder"

Yeah, you're probably right. We can close this issue.
