### ISSUE TITLE
`CARGO_WORKSPACE_DIR` not set during runtime error when crates are exported

### ISSUE THREAD

**Issue by da-bao-jian** [Vid201/silius#175]
When crates that have a dependency on `contracts` crate get [exported as packages](https://github.com/qi-protocol/4337-research/blob/6d27b246d5f464c85ffa489b6a5d00dfed8330bd/research/aa-bundler-runner/Cargo.toml#L10), during compilation, one would run into `CARGO_WORKSPACE_DIR` not set during runtime error. 

To work around this, I had to run `export CARGO_WORKSPACE_DIR=/my/specific/directory` before `cargo build` in the terminal. 

Are there ways to work around this in the script?

**Comment by Vid201** [comment]
The way we handle smart contracts could be changed all together - we talked with @zsluedem about that once. At the moment, we are cloning the repo with solidity files - we could use `sol!` from `alloy-rs` instead (https://github.com/alloy-rs/core/tree/main/crates/sol-macro). This way the crate could become more "clean" as well.
