### ISSUE TITLE
`Error while creating bundle: status: Unavailable, message: "User operation pool is not available"` on official example

### ISSUE THREAD

**Issue by shunkakinoki** [Vid201/silius#202]
Hi! Thank you for providing this wonderful bundler

I'm getting the below error running the official example at `make silius` - any ideas for a fix?

<img width="1645" alt="Screenshot 2023-08-22 at 23 50 11" src="https://github.com/Vid201/silius/assets/39187513/05cab0a1-523c-4c04-9a9c-82a056bfd375">

**Comment by shunkakinoki** [comment]
Followed the instructions in the `README.md` and killed existing ports and was able to fix!

1. Use `geth` with `[debug_traceCall](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debug_tracecall)`, not `anvil`
2. Kill the ports that take up `3000`, `3001`, `3002`

**Comment by Vid201** [comment]
> Followed the instructions in the `README.md` and killed existing ports and was able to fix!
> 
> 1. Use `geth` with `[debug_traceCall](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debug_tracecall)`, not `anvil`
> 2. Kill the ports that take up `3000`, `3001`, `3002`

That's great. Yeah, these ports must be free and `anvil` doesn't support `debug_traceCall` endpoint yet, so `geth` must be used.
