### ISSUE TITLE
User Operations simulations

### ISSUE THREAD

**Issue by Vid201** [Vid201/silius#47]
This issue tracks work on simulation of user operations. Everything is explained here: https://eips.ethereum.org/EIPS/eip-4337#simulation

JS Tracer is needed to perform simulation.

**Comment by Vid201** [comment]
- [x] forbidden opcodes
- [ ] special handling of forbidden opcodes for staked entities
- [ ] GAS opcodes
- [ ] storage access
- [ ] CALL opcodes
- [ ] EXTCODEHASH doesn't change between first and second simulation
- [ ] EXT opcodes
- [ ] only one CREATE2 allowed

https://eips.ethereum.org/EIPS/eip-4337#simulation

@zsluedem

**Comment by zsluedem** [comment]
Very nice!!!!
