### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by Vid201** [Vid201/silius#50]
Improve error handling and make it consistent throughout the codebase

**Comment by brohamgoham** [comment]
Hey I would love to contribute to this project. I read your article @Vid201 https://hackmd.io/@Vid201/aa-bundler-rust and running the bundler locally

**Comment by Vid201** [comment]
> Hey I would love to contribute to this project. I read your article @Vid201 https://hackmd.io/@Vid201/aa-bundler-rust and running the bundler locally

Cool, this issue is also free to take.

**Comment by Vid201** [comment]
@brohamgoham The goal here is to move error objects to separate file, simplify (or move) error conversion (grpc erros and other error types) and in a consistent way throughout the codebase.

**Comment by brohamgoham** [comment]
> @brohamgoham The goal here is to move error objects to separate file, simplify (or move) error conversion (grpc erros and other error types) and in a consistent way throughout the codebase.

Ok thank you, was just getting my branch started.
