### ISSUE TITLE
Abstract sanity check and simulation rules 

### ISSUE THREAD

**Issue by Vid201** [Vid201/silius#51]
Alternative mempools (that is not canonical mempool) can use only subset of all sanity check and simulation rules, e.g., only forbidden opcodes. They can also introduce new custom rules that are specific to them.

We should have a way modular way of enabling/turning on certain rules and add way to write custom rules and include them in the verification/validation workflow.

When bundler will received user operation, it will have to match to which alt mempool the user operation should be passed.

**Comment by Vid201** [comment]
Look at: https://github.com/paradigmxyz/reth/blob/main/crates/transaction-pool/src/validate.rs#L30

**Comment by Vid201** [comment]
Something similar for alt mempools: https://github.com/paradigmxyz/reth/blob/main/crates/transaction-pool/src/validate.rs#L111

**Comment by Vid201** [comment]
**Proposal**

Create two traits: `trait SanityCheck` and `trait SimulationCheck`. All the checks implement one of these two traits.

Create `trait UserOperationValidator` that has function definition `fn verify_user_operation`.

Create `struct CanonicalUserOperationValidator` where you can select all the necessary checks:

`CanonicalUserOperationValidator::new()
.set_sanity_check(SenderOrInitCodeCheck::new())
.set_sanity_check(VerificationGasCheck::new())
.set_simulation_check(StorageAccessCheck::new(whitelisted_slots: [...]))
.set_simulation_check(ForbiddenOpcodesCheck::new(ForbiddenOpcodes::default()))
.set_simulation_check(SignatureCheck::new())`

This is just a first and brief description. What do you think @zsluedem ?

**Comment by zsluedem** [comment]
> `Create two traits: trait SanityCheck and trait SimulationCheck. All the checks implement one of these two traits.`

What is the difference between these two checks?(In the perspective of function signature) 

Could that be more general just one trait `CrazyCheck`?

**Comment by Vid201** [comment]
> > `Create two traits: trait SanityCheck and trait SimulationCheck. All the checks implement one of these two traits.`
> 
> What is the difference between these two checks?(In the perspective of function signature)
> 
> Could that be more general just one trait `Check`?

Hmmm, good point. We can probably merge this into single trait.
